### ISSUE TITLE
could not parse json & could not find cityid 

### ISSUE THREAD

**Issue by Johannes-ece** [DanielStefanK/kleinanzeigen-alert#6]
With the example command "/add Fahrrad, Köln, 20"
I get these two errors: 
"could not parse json"
"could not find cityid" 
Happens with every other command too.

I have honestly no experience with go so I dort really know why its causing this.

**Comment by DanielStefanK** [comment]
Are you trying to self-host the application or are you using my hosted verion?
The query `/add Fahrrad, Köln, 20` works for me at the moment.

**Comment by Johannes-ece** [comment]
I am  trying to self host it

**Comment by Johannes-ece** [comment]
Comparing it to your hosted application, the only obvious difference is that this message is missing for me:
https://ibb.co/WgD4w3W
But it might just be the description of the bot, which I dont have, so I am not really sure about that.

**Comment by Johannes-ece** [comment]
the log:
> 2021/07/21 07:52:36 Fetching ads
> 2021/07/21 07:52:43 Got msg: /start
> 2021/07/21 07:52:49 Got msg: /add Fahrrad, Köln, 20
> 2021/07/21 07:52:49 could not parse json
> 2021/07/21 07:52:49 could not find cityid

**Comment by DanielStefanK** [comment]
Okay just tried to run the app on a different clean machine and it works:

- `git clone https://github.com/DanielStefanK/kleinanzeigen-alert.git kl && cd kl`
- `export TELEGRAM_APITOKEN=<secret token>`
- `go get`
- `go run main.go`

What go version are you using?

**Comment by Johannes-ece** [comment]
I am using the last stable version, 

> export TELEGRAM_APITOKEN=<secret token>
doesnt really work, dont know why, error:
> -bash: syntax error near unexpected token `newline'
Instead I did this in the main.go:
> func main() {
> 	os.Setenv("TELEGRAM_APITOKEN", "194346595**********************************")
> 	token = os.Getenv("TELEGRAM_APITOKEN")
I know this isnt elegant at all, but...

but apart from that I did all of that:
> git clone https://github.com/DanielStefanK/kleinanzeigen-alert.git kl && cd kl
> export TELEGRAM_APITOKEN=<secret token>
> go get
> go run main.go

**Comment by DanielStefanK** [comment]
Okay, I'll look further into this.
What is your os?

I fixed the docker-compose file to support directly building the image. Maybe try this if you have docker and docker-compose installed by putting your token in the `docker-compose.yaml` and running `docker-compose up`.
But be aware that the DB file is stored in the container and will be removed if you not store it in a volume.

**Comment by Johannes-ece** [comment]
ubuntu is my os.
Just tried it with `docker-compose up`
and now I get this error:

```

Step 6/7 : RUN go install github.com/danielstefank/kleinanzeigen-alert/
 ---> Running in ee5f8084314d
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:129019:10: warning: function may return address of local variable [-Wreturn-local-addr]
129019 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128979:10: note: declared here
128979 |   Select standin;
       |          ^~~~~~~
Removing intermediate container ee5f8084314d
 ---> 82a0785440fd
Step 7/7 : ENTRYPOINT ["/go/bin/kleinanzeigen-alert"]
 ---> Running in 6e5bf63bd3e2
Removing intermediate container 6e5bf63bd3e2
 ---> ae4e873e1e30
Successfully built ae4e873e1e30
Successfully tagged kleinanzeigen-alert_kleinanzeigen:latest
Creating kleinanzeigen-alert_kleinanzeigen_1 ... done
Attaching to kleinanzeigen-alert_kleinanzeigen_1
kleinanzeigen_1  | 2021/07/21 09:26:05 could not initalize bot
kleinanzeigen_1  | panic: could not initalize bot
kleinanzeigen_1  | 
kleinanzeigen_1  | goroutine 1 [running]:
kleinanzeigen_1  | log.Panic(0xc0001d1db0, 0x1, 0x1)
kleinanzeigen_1  |      /usr/local/go/src/log/log.go:354 +0xae
kleinanzeigen_1  | github.com/danielstefank/kleinanzeigen-alert/pkg/telegram.(*Bot).Init(0xc00015bfa0)
kleinanzeigen_1  |      /go/src/github.com/danielstefank/kleinanzeigen-alert/pkg/telegram/commandHandler.go:40 +0xd7
kleinanzeigen_1  | main.main()
kleinanzeigen_1  |      /go/src/github.com/danielstefank/kleinanzeigen-alert/main.go:27 +0x130
root@ubuntu-s-1vcpu-1gb-fra1-01:~/kleinanzeigen-alert# 

```

**Comment by DanielStefanK** [comment]
did you replace `myToken` in `docker-compose.yaml`?

**Comment by Johannes-ece** [comment]
yes:
```
version: '3'
services:
  kleinanzeigen:
    build: .
    environment:
      - TELEGRAM_APITOKEN="194346595***************************"
    restart: always

```

**Comment by DanielStefanK** [comment]
Try removing the quotes like this:
```yaml
version: '3'
services:
  kleinanzeigen:
    build: .
    environment:
      - TELEGRAM_APITOKEN=194346595***************************
    restart: always
```

**Comment by Johannes-ece** [comment]
ok, I just made a new droplet(on digitalocean), installed docker and docker-compose
then I ran
```
git clone https://github.com/DanielStefanK/kleinanzeigen-alert.git kl && cd kl
nano docker-compose.yaml // added my  key
docker-compose up
```
I still get the same error :(

I don't want to take up more of your time, since you cant reproduce it and since its probably due to a dumb error of mine...
If you want though, I can recreate the droplet and you try your luck, if so I can send you the ip and key
here´s my email: j.grundherr@pm.me

**Comment by DanielStefanK** [comment]
Problem was found. The error is misleading. On the used server the IP is blocked by Kleinanzeigen. This causes a 403 Error. This error should be used to present a proper log message saying the access to kleinanzeigen was blocked. 
this should probably be done via #8
